export type FilterKey = "city" | "country" | "gender" | "age";

export type FilterOption = {
  value: string;
  label: string;
  code: string;
};

export type DiscoveryFilters = Record<FilterKey, string>;

export const FILTER_TITLES: Record<FilterKey, string> = {
  city: "City",
  country: "Country",
  gender: "Gender",
  age: "Age Group",
};

/** Shared All sentinel — pills show ALL */
export const ALL_OPTION: FilterOption = {
  value: "all",
  label: "All",
  code: "ALL",
};

const COUNTRY_OPTIONS: FilterOption[] = [
  { value: "afghanistan", label: "Afghanistan", code: "AF" },
  { value: "algeria", label: "Algeria", code: "DZ" },
  { value: "argentina", label: "Argentina", code: "AR" },
  { value: "australia", label: "Australia", code: "AU" },
  { value: "austria", label: "Austria", code: "AT" },
  { value: "bahrain", label: "Bahrain", code: "BH" },
  { value: "bangladesh", label: "Bangladesh", code: "BD" },
  { value: "belgium", label: "Belgium", code: "BE" },
  { value: "brazil", label: "Brazil", code: "BR" },
  { value: "canada", label: "Canada", code: "CA" },
  { value: "chile", label: "Chile", code: "CL" },
  { value: "china", label: "China", code: "CN" },
  { value: "colombia", label: "Colombia", code: "CO" },
  { value: "denmark", label: "Denmark", code: "DK" },
  { value: "egypt", label: "Egypt", code: "EG" },
  { value: "finland", label: "Finland", code: "FI" },
  { value: "france", label: "France", code: "FR" },
  { value: "germany", label: "Germany", code: "DE" },
  { value: "ghana", label: "Ghana", code: "GH" },
  { value: "greece", label: "Greece", code: "GR" },
  { value: "hong-kong", label: "Hong Kong", code: "HK" },
  { value: "india", label: "India", code: "IN" },
  { value: "indonesia", label: "Indonesia", code: "ID" },
  { value: "iraq", label: "Iraq", code: "IQ" },
  { value: "ireland", label: "Ireland", code: "IE" },
  { value: "italy", label: "Italy", code: "IT" },
  { value: "japan", label: "Japan", code: "JP" },
  { value: "jordan", label: "Jordan", code: "JO" },
  { value: "kenya", label: "Kenya", code: "KE" },
  { value: "kuwait", label: "Kuwait", code: "KW" },
  { value: "lebanon", label: "Lebanon", code: "LB" },
  { value: "libya", label: "Libya", code: "LY" },
  { value: "malaysia", label: "Malaysia", code: "MY" },
  { value: "mexico", label: "Mexico", code: "MX" },
  { value: "morocco", label: "Morocco", code: "MA" },
  { value: "netherlands", label: "Netherlands", code: "NL" },
  { value: "new-zealand", label: "New Zealand", code: "NZ" },
  { value: "nigeria", label: "Nigeria", code: "NG" },
  { value: "norway", label: "Norway", code: "NO" },
  { value: "oman", label: "Oman", code: "OM" },
  { value: "pakistan", label: "Pakistan", code: "PK" },
  { value: "philippines", label: "Philippines", code: "PH" },
  { value: "poland", label: "Poland", code: "PL" },
  { value: "portugal", label: "Portugal", code: "PT" },
  { value: "qatar", label: "Qatar", code: "QA" },
  { value: "romania", label: "Romania", code: "RO" },
  { value: "saudi-arabia", label: "Saudi Arabia", code: "SA" },
  { value: "singapore", label: "Singapore", code: "SG" },
  { value: "south-africa", label: "South Africa", code: "ZA" },
  { value: "south-korea", label: "South Korea", code: "KR" },
  { value: "spain", label: "Spain", code: "ES" },
  { value: "sri-lanka", label: "Sri Lanka", code: "LK" },
  { value: "sweden", label: "Sweden", code: "SE" },
  { value: "switzerland", label: "Switzerland", code: "CH" },
  { value: "taiwan", label: "Taiwan", code: "TW" },
  { value: "thailand", label: "Thailand", code: "TH" },
  { value: "tunisia", label: "Tunisia", code: "TN" },
  { value: "turkey", label: "Turkey", code: "TR" },
  { value: "uae", label: "United Arab Emirates", code: "AE" },
  { value: "ukraine", label: "Ukraine", code: "UA" },
  { value: "united-kingdom", label: "United Kingdom", code: "UK" },
  { value: "united-states", label: "United States", code: "US" },
  { value: "vietnam", label: "Vietnam", code: "VN" },
];

/** Major cities A–Z per country (users + extras for cascade demo) */
export const CITIES_BY_COUNTRY: Record<string, FilterOption[]> = {
  "afghanistan": [
    { value: "kabul", label: "Kabul", code: "KAB" },
    { value: "herat", label: "Herat", code: "HER" },
    { value: "kandahar", label: "Kandahar", code: "KAN" },
    { value: "mazar-i-sharif", label: "Mazar-i-Sharif", code: "MAZ" },
    { value: "jalalabad", label: "Jalalabad", code: "JAL" },
    { value: "kunduz", label: "Kunduz", code: "KUN" },
    { value: "ghazni", label: "Ghazni", code: "GHA" },
    { value: "balkh", label: "Balkh", code: "BAL" },
    { value: "farah", label: "Farah", code: "FAR" },
    { value: "lashkar-gah", label: "Lashkar Gah", code: "LAS" },
    { value: "puli-khumri", label: "Puli Khumri", code: "PUL" },
    { value: "khost", label: "Khost", code: "KHO" },
    { value: "sheberghan", label: "Sheberghan", code: "SHE" },
    { value: "taloqan", label: "Taloqan", code: "TAL" },
    { value: "charikar", label: "Charikar", code: "CHA" },
    { value: "gardez", label: "Gardez", code: "GAR" },
    { value: "bamyan", label: "Bamyan", code: "BAM" },
    { value: "zaranj", label: "Zaranj", code: "ZAR" },
    { value: "maymana", label: "Maymana", code: "MAY" },
    { value: "asadabad", label: "Asadabad", code: "ASA" },
  ],
  "algeria": [
    { value: "algiers", label: "Algiers", code: "ALG" },
    { value: "oran", label: "Oran", code: "ORA" },
    { value: "constantine", label: "Constantine", code: "CON" },
    { value: "annaba", label: "Annaba", code: "ANN" },
    { value: "blida", label: "Blida", code: "BLI" },
    { value: "batna", label: "Batna", code: "BAT" },
    { value: "setif", label: "Setif", code: "SET" },
    { value: "sidi-bel-abbes", label: "Sidi Bel Abbes", code: "SID" },
    { value: "biskra", label: "Biskra", code: "BIS" },
    { value: "tebessa", label: "Tebessa", code: "TEB" },
    { value: "tlemcen", label: "Tlemcen", code: "TLE" },
    { value: "bejaia", label: "Bejaia", code: "BEJ" },
    { value: "skikda", label: "Skikda", code: "SKI" },
    { value: "tiaret", label: "Tiaret", code: "TIA" },
    { value: "bechar", label: "Bechar", code: "BEC" },
    { value: "mostaganem", label: "Mostaganem", code: "MOS" },
    { value: "el-oued", label: "El Oued", code: "ELO" },
    { value: "chlef", label: "Chlef", code: "CHL" },
    { value: "djelfa", label: "Djelfa", code: "DJE" },
    { value: "jijel", label: "Jijel", code: "JIJ" },
  ],
  "argentina": [
    { value: "buenos-aires", label: "Buenos Aires", code: "BUE" },
    { value: "cordoba", label: "Cordoba", code: "COR" },
    { value: "rosario", label: "Rosario", code: "ROS" },
    { value: "mendoza", label: "Mendoza", code: "MEN" },
    { value: "la-plata", label: "La Plata", code: "LAP" },
    { value: "san-miguel-de-tucuman", label: "San Miguel de Tucuman", code: "SAN" },
    { value: "mar-del-plata", label: "Mar del Plata", code: "MAR" },
    { value: "salta", label: "Salta", code: "SAL" },
    { value: "santa-fe", label: "Santa Fe", code: "SAN" },
    { value: "san-juan", label: "San Juan", code: "SAN" },
    { value: "resistencia", label: "Resistencia", code: "RES" },
    { value: "neuquen", label: "Neuquen", code: "NEU" },
    { value: "santiago-del-estero", label: "Santiago del Estero", code: "SAN" },
    { value: "corrientes", label: "Corrientes", code: "COR" },
    { value: "bahia-blanca", label: "Bahia Blanca", code: "BAH" },
    { value: "posadas", label: "Posadas", code: "POS" },
    { value: "parana", label: "Parana", code: "PAR" },
    { value: "formosa", label: "Formosa", code: "FOR" },
    { value: "san-salvador-de-jujuy", label: "San Salvador de Jujuy", code: "SAN" },
    { value: "rio-cuarto", label: "Rio Cuarto", code: "RIO" },
  ],
  "australia": [
    { value: "sydney", label: "Sydney", code: "SYD" },
    { value: "melbourne", label: "Melbourne", code: "MEL" },
    { value: "brisbane", label: "Brisbane", code: "BRI" },
    { value: "perth", label: "Perth", code: "PER" },
    { value: "adelaide", label: "Adelaide", code: "ADE" },
    { value: "canberra", label: "Canberra", code: "CAN" },
    { value: "gold-coast", label: "Gold Coast", code: "GOL" },
    { value: "newcastle", label: "Newcastle", code: "NEW" },
    { value: "wollongong", label: "Wollongong", code: "WOL" },
    { value: "hobart", label: "Hobart", code: "HOB" },
    { value: "geelong", label: "Geelong", code: "GEE" },
    { value: "townsville", label: "Townsville", code: "TOW" },
    { value: "cairns", label: "Cairns", code: "CAI" },
    { value: "darwin", label: "Darwin", code: "DAR" },
    { value: "toowoomba", label: "Toowoomba", code: "TOO" },
    { value: "ballarat", label: "Ballarat", code: "BAL" },
    { value: "bendigo", label: "Bendigo", code: "BEN" },
    { value: "launceston", label: "Launceston", code: "LAU" },
    { value: "mackay", label: "Mackay", code: "MAC" },
    { value: "albury", label: "Albury", code: "ALB" },
  ],
  "austria": [
    { value: "vienna", label: "Vienna", code: "VIE" },
    { value: "graz", label: "Graz", code: "GRA" },
    { value: "linz", label: "Linz", code: "LIN" },
    { value: "salzburg", label: "Salzburg", code: "SAL" },
    { value: "innsbruck", label: "Innsbruck", code: "INN" },
    { value: "klagenfurt", label: "Klagenfurt", code: "KLA" },
    { value: "villach", label: "Villach", code: "VIL" },
    { value: "wels", label: "Wels", code: "WEL" },
    { value: "sankt-polten", label: "Sankt Polten", code: "SAN" },
    { value: "dornbirn", label: "Dornbirn", code: "DOR" },
    { value: "steyr", label: "Steyr", code: "STE" },
    { value: "wiener-neustadt", label: "Wiener Neustadt", code: "WIE" },
    { value: "feldkirch", label: "Feldkirch", code: "FEL" },
    { value: "bregenz", label: "Bregenz", code: "BRE" },
    { value: "leonding", label: "Leonding", code: "LEO" },
    { value: "klosterneuburg", label: "Klosterneuburg", code: "KLO" },
    { value: "baden", label: "Baden", code: "BAD" },
    { value: "wolfsberg", label: "Wolfsberg", code: "WOL" },
    { value: "leoben", label: "Leoben", code: "LEO" },
    { value: "krems", label: "Krems", code: "KRE" },
  ],
  "bahrain": [
    { value: "manama", label: "Manama", code: "MAN" },
    { value: "riffa", label: "Riffa", code: "RIF" },
    { value: "muharraq", label: "Muharraq", code: "MUH" },
    { value: "hamad-town", label: "Hamad Town", code: "HAM" },
    { value: "aali", label: "Aali", code: "AAL" },
    { value: "isa-town", label: "Isa Town", code: "ISA" },
    { value: "sitra", label: "Sitra", code: "SIT" },
    { value: "budaiya", label: "Budaiya", code: "BUD" },
    { value: "jidhafs", label: "Jidhafs", code: "JID" },
    { value: "sanabis", label: "Sanabis", code: "SAN" },
    { value: "tubli", label: "Tubli", code: "TUB" },
    { value: "juffair", label: "Juffair", code: "JUF" },
    { value: "seef", label: "Seef", code: "SEE" },
    { value: "amwaj-islands", label: "Amwaj Islands", code: "AMW" },
    { value: "zallaq", label: "Zallaq", code: "ZAL" },
    { value: "dur", label: "Dur", code: "DUR" },
    { value: "askar", label: "Askar", code: "ASK" },
    { value: "hidd", label: "Hidd", code: "HID" },
    { value: "barbar", label: "Barbar", code: "BAR" },
    { value: "saar", label: "Saar", code: "SAA" },
  ],
  "bangladesh": [
    { value: "dhaka", label: "Dhaka", code: "DHA" },
    { value: "chittagong", label: "Chittagong", code: "CHI" },
    { value: "khulna", label: "Khulna", code: "KHU" },
    { value: "rajshahi", label: "Rajshahi", code: "RAJ" },
    { value: "sylhet", label: "Sylhet", code: "SYL" },
    { value: "gazipur", label: "Gazipur", code: "GAZ" },
    { value: "narayanganj", label: "Narayanganj", code: "NAR" },
    { value: "rangpur", label: "Rangpur", code: "RAN" },
    { value: "mymensingh", label: "Mymensingh", code: "MYM" },
    { value: "barisal", label: "Barisal", code: "BAR" },
    { value: "comilla", label: "Comilla", code: "COM" },
    { value: "bogura", label: "Bogura", code: "BOG" },
    { value: "jessore", label: "Jessore", code: "JES" },
    { value: "coxs-bazar", label: "Coxs Bazar", code: "COX" },
    { value: "dinajpur", label: "Dinajpur", code: "DIN" },
    { value: "tangail", label: "Tangail", code: "TAN" },
    { value: "pabna", label: "Pabna", code: "PAB" },
    { value: "narsingdi", label: "Narsingdi", code: "NAR" },
    { value: "faridpur", label: "Faridpur", code: "FAR" },
    { value: "kushtia", label: "Kushtia", code: "KUS" },
  ],
  "belgium": [
    { value: "brussels", label: "Brussels", code: "BRU" },
    { value: "antwerp", label: "Antwerp", code: "ANT" },
    { value: "ghent", label: "Ghent", code: "GHE" },
    { value: "charleroi", label: "Charleroi", code: "CHA" },
    { value: "liege", label: "Liege", code: "LIE" },
    { value: "bruges", label: "Bruges", code: "BRU" },
    { value: "namur", label: "Namur", code: "NAM" },
    { value: "leuven", label: "Leuven", code: "LEU" },
    { value: "mons", label: "Mons", code: "MON" },
    { value: "mechelen", label: "Mechelen", code: "MEC" },
    { value: "aalst", label: "Aalst", code: "AAL" },
    { value: "la-louviere", label: "La Louviere", code: "LAL" },
    { value: "kortrijk", label: "Kortrijk", code: "KOR" },
    { value: "hasselt", label: "Hasselt", code: "HAS" },
    { value: "ostend", label: "Ostend", code: "OST" },
    { value: "tournai", label: "Tournai", code: "TOU" },
    { value: "genk", label: "Genk", code: "GEN" },
    { value: "seraing", label: "Seraing", code: "SER" },
    { value: "roeselare", label: "Roeselare", code: "ROE" },
    { value: "verviers", label: "Verviers", code: "VER" },
  ],
  "brazil": [
    { value: "sao-paulo", label: "Sao Paulo", code: "SAO" },
    { value: "rio-de-janeiro", label: "Rio de Janeiro", code: "RIO" },
    { value: "brasilia", label: "Brasilia", code: "BRA" },
    { value: "salvador", label: "Salvador", code: "SAL" },
    { value: "fortaleza", label: "Fortaleza", code: "FOR" },
    { value: "belo-horizonte", label: "Belo Horizonte", code: "BEL" },
    { value: "manaus", label: "Manaus", code: "MAN" },
    { value: "curitiba", label: "Curitiba", code: "CUR" },
    { value: "recife", label: "Recife", code: "REC" },
    { value: "porto-alegre", label: "Porto Alegre", code: "POR" },
    { value: "belem", label: "Belem", code: "BEL" },
    { value: "goiania", label: "Goiania", code: "GOI" },
    { value: "guarulhos", label: "Guarulhos", code: "GUA" },
    { value: "campinas", label: "Campinas", code: "CAM" },
    { value: "sao-luis", label: "Sao Luis", code: "SAO" },
    { value: "sao-goncalo", label: "Sao Goncalo", code: "SAO" },
    { value: "maceio", label: "Maceio", code: "MAC" },
    { value: "duque-de-caxias", label: "Duque de Caxias", code: "DUQ" },
    { value: "natal", label: "Natal", code: "NAT" },
    { value: "teresina", label: "Teresina", code: "TER" },
  ],
  "canada": [
    { value: "toronto", label: "Toronto", code: "TOR" },
    { value: "montreal", label: "Montreal", code: "MON" },
    { value: "vancouver", label: "Vancouver", code: "VAN" },
    { value: "calgary", label: "Calgary", code: "CAL" },
    { value: "edmonton", label: "Edmonton", code: "EDM" },
    { value: "ottawa", label: "Ottawa", code: "OTT" },
    { value: "winnipeg", label: "Winnipeg", code: "WIN" },
    { value: "quebec-city", label: "Quebec City", code: "QUE" },
    { value: "hamilton", label: "Hamilton", code: "HAM" },
    { value: "kitchener", label: "Kitchener", code: "KIT" },
    { value: "london", label: "London", code: "LON" },
    { value: "victoria", label: "Victoria", code: "VIC" },
    { value: "halifax", label: "Halifax", code: "HAL" },
    { value: "oshawa", label: "Oshawa", code: "OSH" },
    { value: "windsor", label: "Windsor", code: "WIN" },
    { value: "saskatoon", label: "Saskatoon", code: "SAS" },
    { value: "regina", label: "Regina", code: "REG" },
    { value: "st-johns", label: "St Johns", code: "STJ" },
    { value: "kelowna", label: "Kelowna", code: "KEL" },
    { value: "barrie", label: "Barrie", code: "BAR" },
  ],
  "chile": [
    { value: "santiago", label: "Santiago", code: "SAN" },
    { value: "valparaiso", label: "Valparaiso", code: "VAL" },
    { value: "concepcion", label: "Concepcion", code: "CON" },
    { value: "la-serena", label: "La Serena", code: "LAS" },
    { value: "antofagasta", label: "Antofagasta", code: "ANT" },
    { value: "temuco", label: "Temuco", code: "TEM" },
    { value: "rancagua", label: "Rancagua", code: "RAN" },
    { value: "talca", label: "Talca", code: "TAL" },
    { value: "arica", label: "Arica", code: "ARI" },
    { value: "iquique", label: "Iquique", code: "IQU" },
    { value: "puerto-montt", label: "Puerto Montt", code: "PUE" },
    { value: "coquimbo", label: "Coquimbo", code: "COQ" },
    { value: "chillan", label: "Chillan", code: "CHI" },
    { value: "osorno", label: "Osorno", code: "OSO" },
    { value: "valdivia", label: "Valdivia", code: "VAL" },
    { value: "punta-arenas", label: "Punta Arenas", code: "PUN" },
    { value: "calama", label: "Calama", code: "CAL" },
    { value: "quilpue", label: "Quilpue", code: "QUI" },
    { value: "vina-del-mar", label: "Vina del Mar", code: "VIN" },
    { value: "los-angeles", label: "Los Angeles", code: "LOS" },
  ],
  "china": [
    { value: "beijing", label: "Beijing", code: "BEI" },
    { value: "shanghai", label: "Shanghai", code: "SHA" },
    { value: "guangzhou", label: "Guangzhou", code: "GUA" },
    { value: "shenzhen", label: "Shenzhen", code: "SHE" },
    { value: "chengdu", label: "Chengdu", code: "CHE" },
    { value: "chongqing", label: "Chongqing", code: "CHO" },
    { value: "hangzhou", label: "Hangzhou", code: "HAN" },
    { value: "wuhan", label: "Wuhan", code: "WUH" },
    { value: "xian", label: "Xian", code: "XIA" },
    { value: "nanjing", label: "Nanjing", code: "NAN" },
    { value: "tianjin", label: "Tianjin", code: "TIA" },
    { value: "suzhou", label: "Suzhou", code: "SUZ" },
    { value: "zhengzhou", label: "Zhengzhou", code: "ZHE" },
    { value: "changsha", label: "Changsha", code: "CHA" },
    { value: "dongguan", label: "Dongguan", code: "DON" },
    { value: "qingdao", label: "Qingdao", code: "QIN" },
    { value: "dalian", label: "Dalian", code: "DAL" },
    { value: "ningbo", label: "Ningbo", code: "NIN" },
    { value: "xiamen", label: "Xiamen", code: "XIA" },
    { value: "kunming", label: "Kunming", code: "KUN" },
    { value: "fuzhou", label: "Fuzhou", code: "FUZ" },
    { value: "harbin", label: "Harbin", code: "HAR" },
    { value: "jinan", label: "Jinan", code: "JIN" },
    { value: "hefei", label: "Hefei", code: "HEF" },
  ],
  "colombia": [
    { value: "bogota", label: "Bogota", code: "BOG" },
    { value: "medellin", label: "Medellin", code: "MED" },
    { value: "cali", label: "Cali", code: "CAL" },
    { value: "barranquilla", label: "Barranquilla", code: "BAR" },
    { value: "cartagena", label: "Cartagena", code: "CAR" },
    { value: "cucuta", label: "Cucuta", code: "CUC" },
    { value: "bucaramanga", label: "Bucaramanga", code: "BUC" },
    { value: "pereira", label: "Pereira", code: "PER" },
    { value: "santa-marta", label: "Santa Marta", code: "SAN" },
    { value: "ibague", label: "Ibague", code: "IBA" },
    { value: "manizales", label: "Manizales", code: "MAN" },
    { value: "pasto", label: "Pasto", code: "PAS" },
    { value: "villavicencio", label: "Villavicencio", code: "VIL" },
    { value: "monteria", label: "Monteria", code: "MON" },
    { value: "valledupar", label: "Valledupar", code: "VAL" },
    { value: "neiva", label: "Neiva", code: "NEI" },
    { value: "armenia", label: "Armenia", code: "ARM" },
    { value: "sincelejo", label: "Sincelejo", code: "SIN" },
    { value: "popayan", label: "Popayan", code: "POP" },
    { value: "tunja", label: "Tunja", code: "TUN" },
  ],
  "denmark": [
    { value: "copenhagen", label: "Copenhagen", code: "COP" },
    { value: "aarhus", label: "Aarhus", code: "AAR" },
    { value: "odense", label: "Odense", code: "ODE" },
    { value: "aalborg", label: "Aalborg", code: "AAL" },
    { value: "esbjerg", label: "Esbjerg", code: "ESB" },
    { value: "randers", label: "Randers", code: "RAN" },
    { value: "kolding", label: "Kolding", code: "KOL" },
    { value: "horsens", label: "Horsens", code: "HOR" },
    { value: "vejle", label: "Vejle", code: "VEJ" },
    { value: "roskilde", label: "Roskilde", code: "ROS" },
    { value: "herning", label: "Herning", code: "HER" },
    { value: "silkeborg", label: "Silkeborg", code: "SIL" },
    { value: "naestved", label: "Naestved", code: "NAE" },
    { value: "fredericia", label: "Fredericia", code: "FRE" },
    { value: "viborg", label: "Viborg", code: "VIB" },
    { value: "koge", label: "Koge", code: "KOG" },
    { value: "holstebro", label: "Holstebro", code: "HOL" },
    { value: "taastrup", label: "Taastrup", code: "TAA" },
    { value: "slagelse", label: "Slagelse", code: "SLA" },
    { value: "hillerod", label: "Hillerod", code: "HIL" },
  ],
  "egypt": [
    { value: "cairo", label: "Cairo", code: "CAI" },
    { value: "alexandria", label: "Alexandria", code: "ALE" },
    { value: "giza", label: "Giza", code: "GIZ" },
    { value: "shubra-el-kheima", label: "Shubra El Kheima", code: "SHU" },
    { value: "port-said", label: "Port Said", code: "POR" },
    { value: "suez", label: "Suez", code: "SUE" },
    { value: "luxor", label: "Luxor", code: "LUX" },
    { value: "mansoura", label: "Mansoura", code: "MAN" },
    { value: "tanta", label: "Tanta", code: "TAN" },
    { value: "asyut", label: "Asyut", code: "ASY" },
    { value: "ismailia", label: "Ismailia", code: "ISM" },
    { value: "fayoum", label: "Fayoum", code: "FAY" },
    { value: "zagazig", label: "Zagazig", code: "ZAG" },
    { value: "aswan", label: "Aswan", code: "ASW" },
    { value: "damietta", label: "Damietta", code: "DAM" },
    { value: "minya", label: "Minya", code: "MIN" },
    { value: "damanhur", label: "Damanhur", code: "DAM" },
    { value: "beni-suef", label: "Beni Suef", code: "BEN" },
    { value: "qena", label: "Qena", code: "QEN" },
    { value: "sohag", label: "Sohag", code: "SOH" },
  ],
  "finland": [
    { value: "helsinki", label: "Helsinki", code: "HEL" },
    { value: "espoo", label: "Espoo", code: "ESP" },
    { value: "tampere", label: "Tampere", code: "TAM" },
    { value: "vantaa", label: "Vantaa", code: "VAN" },
    { value: "oulu", label: "Oulu", code: "OUL" },
    { value: "turku", label: "Turku", code: "TUR" },
    { value: "jyvaskyla", label: "Jyvaskyla", code: "JYV" },
    { value: "lahti", label: "Lahti", code: "LAH" },
    { value: "kuopio", label: "Kuopio", code: "KUO" },
    { value: "pori", label: "Pori", code: "POR" },
    { value: "kouvola", label: "Kouvola", code: "KOU" },
    { value: "joensuu", label: "Joensuu", code: "JOE" },
    { value: "lappeenranta", label: "Lappeenranta", code: "LAP" },
    { value: "hameenlinna", label: "Hameenlinna", code: "HAM" },
    { value: "vaasa", label: "Vaasa", code: "VAA" },
    { value: "seinajoki", label: "Seinajoki", code: "SEI" },
    { value: "rovaniemi", label: "Rovaniemi", code: "ROV" },
    { value: "mikkeli", label: "Mikkeli", code: "MIK" },
    { value: "kotka", label: "Kotka", code: "KOT" },
    { value: "salo", label: "Salo", code: "SAL" },
  ],
  "france": [
    { value: "paris", label: "Paris", code: "PAR" },
    { value: "marseille", label: "Marseille", code: "MAR" },
    { value: "lyon", label: "Lyon", code: "LYO" },
    { value: "toulouse", label: "Toulouse", code: "TOU" },
    { value: "nice", label: "Nice", code: "NIC" },
    { value: "nantes", label: "Nantes", code: "NAN" },
    { value: "strasbourg", label: "Strasbourg", code: "STR" },
    { value: "montpellier", label: "Montpellier", code: "MON" },
    { value: "bordeaux", label: "Bordeaux", code: "BOR" },
    { value: "lille", label: "Lille", code: "LIL" },
    { value: "rennes", label: "Rennes", code: "REN" },
    { value: "reims", label: "Reims", code: "REI" },
    { value: "saint-etienne", label: "Saint-Etienne", code: "SAI" },
    { value: "le-havre", label: "Le Havre", code: "LEH" },
    { value: "toulon", label: "Toulon", code: "TOU" },
    { value: "grenoble", label: "Grenoble", code: "GRE" },
    { value: "dijon", label: "Dijon", code: "DIJ" },
    { value: "angers", label: "Angers", code: "ANG" },
    { value: "nimes", label: "Nimes", code: "NIM" },
    { value: "villeurbanne", label: "Villeurbanne", code: "VIL" },
  ],
  "germany": [
    { value: "berlin", label: "Berlin", code: "BER" },
    { value: "hamburg", label: "Hamburg", code: "HAM" },
    { value: "munich", label: "Munich", code: "MUN" },
    { value: "cologne", label: "Cologne", code: "COL" },
    { value: "frankfurt", label: "Frankfurt", code: "FRA" },
    { value: "stuttgart", label: "Stuttgart", code: "STU" },
    { value: "dusseldorf", label: "Dusseldorf", code: "DUS" },
    { value: "leipzig", label: "Leipzig", code: "LEI" },
    { value: "dortmund", label: "Dortmund", code: "DOR" },
    { value: "essen", label: "Essen", code: "ESS" },
    { value: "bremen", label: "Bremen", code: "BRE" },
    { value: "dresden", label: "Dresden", code: "DRE" },
    { value: "hannover", label: "Hannover", code: "HAN" },
    { value: "nuremberg", label: "Nuremberg", code: "NUR" },
    { value: "duisburg", label: "Duisburg", code: "DUI" },
    { value: "bochum", label: "Bochum", code: "BOC" },
    { value: "wuppertal", label: "Wuppertal", code: "WUP" },
    { value: "bielefeld", label: "Bielefeld", code: "BIE" },
    { value: "bonn", label: "Bonn", code: "BON" },
    { value: "munster", label: "Munster", code: "MUN" },
  ],
  "ghana": [
    { value: "accra", label: "Accra", code: "ACC" },
    { value: "kumasi", label: "Kumasi", code: "KUM" },
    { value: "tamale", label: "Tamale", code: "TAM" },
    { value: "takoradi", label: "Takoradi", code: "TAK" },
    { value: "ashaiman", label: "Ashaiman", code: "ASH" },
    { value: "cape-coast", label: "Cape Coast", code: "CAP" },
    { value: "obuasi", label: "Obuasi", code: "OBU" },
    { value: "tema", label: "Tema", code: "TEM" },
    { value: "teshie", label: "Teshie", code: "TES" },
    { value: "madina", label: "Madina", code: "MAD" },
    { value: "koforidua", label: "Koforidua", code: "KOF" },
    { value: "wa", label: "Wa", code: "WA" },
    { value: "sunyani", label: "Sunyani", code: "SUN" },
    { value: "ho", label: "Ho", code: "HO" },
    { value: "techiman", label: "Techiman", code: "TEC" },
    { value: "nkawkaw", label: "Nkawkaw", code: "NKA" },
    { value: "winneba", label: "Winneba", code: "WIN" },
    { value: "bolgatanga", label: "Bolgatanga", code: "BOL" },
    { value: "kasoa", label: "Kasoa", code: "KAS" },
    { value: "dunkwa", label: "Dunkwa", code: "DUN" },
  ],
  "greece": [
    { value: "athens", label: "Athens", code: "ATH" },
    { value: "thessaloniki", label: "Thessaloniki", code: "THE" },
    { value: "patras", label: "Patras", code: "PAT" },
    { value: "heraklion", label: "Heraklion", code: "HER" },
    { value: "larissa", label: "Larissa", code: "LAR" },
    { value: "volos", label: "Volos", code: "VOL" },
    { value: "rhodes", label: "Rhodes", code: "RHO" },
    { value: "ioannina", label: "Ioannina", code: "IOA" },
    { value: "chania", label: "Chania", code: "CHA" },
    { value: "chalcis", label: "Chalcis", code: "CHA" },
    { value: "agrinio", label: "Agrinio", code: "AGR" },
    { value: "kalamata", label: "Kalamata", code: "KAL" },
    { value: "kavala", label: "Kavala", code: "KAV" },
    { value: "serres", label: "Serres", code: "SER" },
    { value: "alexandroupoli", label: "Alexandroupoli", code: "ALE" },
    { value: "xanthi", label: "Xanthi", code: "XAN" },
    { value: "katerini", label: "Katerini", code: "KAT" },
    { value: "trikala", label: "Trikala", code: "TRI" },
    { value: "lamia", label: "Lamia", code: "LAM" },
    { value: "komotini", label: "Komotini", code: "KOM" },
  ],
  "hong-kong": [
    { value: "central", label: "Central", code: "CEN" },
    { value: "tsim-sha-tsui", label: "Tsim Sha Tsui", code: "TSI" },
    { value: "mong-kok", label: "Mong Kok", code: "MON" },
    { value: "causeway-bay", label: "Causeway Bay", code: "CAU" },
    { value: "wan-chai", label: "Wan Chai", code: "WAN" },
    { value: "sha-tin", label: "Sha Tin", code: "SHA" },
    { value: "tsuen-wan", label: "Tsuen Wan", code: "TSU" },
    { value: "yuen-long", label: "Yuen Long", code: "YUE" },
    { value: "tuen-mun", label: "Tuen Mun", code: "TUE" },
    { value: "tai-po", label: "Tai Po", code: "TAI" },
    { value: "kwun-tong", label: "Kwun Tong", code: "KWU" },
    { value: "kowloon-city", label: "Kowloon City", code: "KOW" },
    { value: "aberdeen", label: "Aberdeen", code: "ABE" },
    { value: "sai-kung", label: "Sai Kung", code: "SAI" },
    { value: "north-point", label: "North Point", code: "NOR" },
    { value: "quarry-bay", label: "Quarry Bay", code: "QUA" },
    { value: "hung-hom", label: "Hung Hom", code: "HUN" },
    { value: "jordan", label: "Jordan", code: "JOR" },
    { value: "sheung-wan", label: "Sheung Wan", code: "SHE" },
    { value: "admiralty", label: "Admiralty", code: "ADM" },
  ],
  "india": [
    { value: "mumbai", label: "Mumbai", code: "MUM" },
    { value: "delhi", label: "Delhi", code: "DEL" },
    { value: "bangalore", label: "Bangalore", code: "BAN" },
    { value: "hyderabad", label: "Hyderabad", code: "HYD" },
    { value: "chennai", label: "Chennai", code: "CHE" },
    { value: "kolkata", label: "Kolkata", code: "KOL" },
    { value: "pune", label: "Pune", code: "PUN" },
    { value: "ahmedabad", label: "Ahmedabad", code: "AHM" },
    { value: "jaipur", label: "Jaipur", code: "JAI" },
    { value: "surat", label: "Surat", code: "SUR" },
    { value: "lucknow", label: "Lucknow", code: "LUC" },
    { value: "kanpur", label: "Kanpur", code: "KAN" },
    { value: "nagpur", label: "Nagpur", code: "NAG" },
    { value: "indore", label: "Indore", code: "IND" },
    { value: "thane", label: "Thane", code: "THA" },
    { value: "bhopal", label: "Bhopal", code: "BHO" },
    { value: "visakhapatnam", label: "Visakhapatnam", code: "VIS" },
    { value: "patna", label: "Patna", code: "PAT" },
    { value: "vadodara", label: "Vadodara", code: "VAD" },
    { value: "ghaziabad", label: "Ghaziabad", code: "GHA" },
    { value: "ludhiana", label: "Ludhiana", code: "LUD" },
    { value: "agra", label: "Agra", code: "AGR" },
    { value: "nashik", label: "Nashik", code: "NAS" },
    { value: "faridabad", label: "Faridabad", code: "FAR" },
  ],
  "indonesia": [
    { value: "jakarta", label: "Jakarta", code: "JAK" },
    { value: "surabaya", label: "Surabaya", code: "SUR" },
    { value: "bandung", label: "Bandung", code: "BAN" },
    { value: "medan", label: "Medan", code: "MED" },
    { value: "semarang", label: "Semarang", code: "SEM" },
    { value: "makassar", label: "Makassar", code: "MAK" },
    { value: "palembang", label: "Palembang", code: "PAL" },
    { value: "depok", label: "Depok", code: "DEP" },
    { value: "tangerang", label: "Tangerang", code: "TAN" },
    { value: "bekasi", label: "Bekasi", code: "BEK" },
    { value: "batam", label: "Batam", code: "BAT" },
    { value: "bogor", label: "Bogor", code: "BOG" },
    { value: "pekanbaru", label: "Pekanbaru", code: "PEK" },
    { value: "padang", label: "Padang", code: "PAD" },
    { value: "malang", label: "Malang", code: "MAL" },
    { value: "samarinda", label: "Samarinda", code: "SAM" },
    { value: "denpasar", label: "Denpasar", code: "DEN" },
    { value: "balikpapan", label: "Balikpapan", code: "BAL" },
    { value: "yogyakarta", label: "Yogyakarta", code: "YOG" },
    { value: "pontianak", label: "Pontianak", code: "PON" },
  ],
  "iraq": [
    { value: "baghdad", label: "Baghdad", code: "BAG" },
    { value: "basra", label: "Basra", code: "BAS" },
    { value: "mosul", label: "Mosul", code: "MOS" },
    { value: "erbil", label: "Erbil", code: "ERB" },
    { value: "kirkuk", label: "Kirkuk", code: "KIR" },
    { value: "najaf", label: "Najaf", code: "NAJ" },
    { value: "karbala", label: "Karbala", code: "KAR" },
    { value: "sulaymaniyah", label: "Sulaymaniyah", code: "SUL" },
    { value: "nasiriyah", label: "Nasiriyah", code: "NAS" },
    { value: "amarah", label: "Amarah", code: "AMA" },
    { value: "diwaniyah", label: "Diwaniyah", code: "DIW" },
    { value: "ramadi", label: "Ramadi", code: "RAM" },
    { value: "fallujah", label: "Fallujah", code: "FAL" },
    { value: "kut", label: "Kut", code: "KUT" },
    { value: "dohuk", label: "Dohuk", code: "DOH" },
    { value: "baqubah", label: "Baqubah", code: "BAQ" },
    { value: "samawah", label: "Samawah", code: "SAM" },
    { value: "tikrit", label: "Tikrit", code: "TIK" },
    { value: "hilla", label: "Hilla", code: "HIL" },
    { value: "zakho", label: "Zakho", code: "ZAK" },
  ],
  "ireland": [
    { value: "dublin", label: "Dublin", code: "DUB" },
    { value: "cork", label: "Cork", code: "COR" },
    { value: "limerick", label: "Limerick", code: "LIM" },
    { value: "galway", label: "Galway", code: "GAL" },
    { value: "waterford", label: "Waterford", code: "WAT" },
    { value: "drogheda", label: "Drogheda", code: "DRO" },
    { value: "dundalk", label: "Dundalk", code: "DUN" },
    { value: "swords", label: "Swords", code: "SWO" },
    { value: "bray", label: "Bray", code: "BRA" },
    { value: "navan", label: "Navan", code: "NAV" },
    { value: "ennis", label: "Ennis", code: "ENN" },
    { value: "kilkenny", label: "Kilkenny", code: "KIL" },
    { value: "carlow", label: "Carlow", code: "CAR" },
    { value: "tralee", label: "Tralee", code: "TRA" },
    { value: "newbridge", label: "Newbridge", code: "NEW" },
    { value: "portlaoise", label: "Portlaoise", code: "POR" },
    { value: "balbriggan", label: "Balbriggan", code: "BAL" },
    { value: "naas", label: "Naas", code: "NAA" },
    { value: "athlone", label: "Athlone", code: "ATH" },
    { value: "mullingar", label: "Mullingar", code: "MUL" },
  ],
  "italy": [
    { value: "rome", label: "Rome", code: "ROM" },
    { value: "milan", label: "Milan", code: "MIL" },
    { value: "naples", label: "Naples", code: "NAP" },
    { value: "turin", label: "Turin", code: "TUR" },
    { value: "palermo", label: "Palermo", code: "PAL" },
    { value: "genoa", label: "Genoa", code: "GEN" },
    { value: "bologna", label: "Bologna", code: "BOL" },
    { value: "florence", label: "Florence", code: "FLO" },
    { value: "bari", label: "Bari", code: "BAR" },
    { value: "catania", label: "Catania", code: "CAT" },
    { value: "venice", label: "Venice", code: "VEN" },
    { value: "verona", label: "Verona", code: "VER" },
    { value: "messina", label: "Messina", code: "MES" },
    { value: "padua", label: "Padua", code: "PAD" },
    { value: "trieste", label: "Trieste", code: "TRI" },
    { value: "brescia", label: "Brescia", code: "BRE" },
    { value: "parma", label: "Parma", code: "PAR" },
    { value: "taranto", label: "Taranto", code: "TAR" },
    { value: "prato", label: "Prato", code: "PRA" },
    { value: "modena", label: "Modena", code: "MOD" },
  ],
  "japan": [
    { value: "tokyo", label: "Tokyo", code: "TOK" },
    { value: "yokohama", label: "Yokohama", code: "YOK" },
    { value: "osaka", label: "Osaka", code: "OSA" },
    { value: "nagoya", label: "Nagoya", code: "NAG" },
    { value: "sapporo", label: "Sapporo", code: "SAP" },
    { value: "fukuoka", label: "Fukuoka", code: "FUK" },
    { value: "kobe", label: "Kobe", code: "KOB" },
    { value: "kyoto", label: "Kyoto", code: "KYO" },
    { value: "kawasaki", label: "Kawasaki", code: "KAW" },
    { value: "saitama", label: "Saitama", code: "SAI" },
    { value: "hiroshima", label: "Hiroshima", code: "HIR" },
    { value: "sendai", label: "Sendai", code: "SEN" },
    { value: "chiba", label: "Chiba", code: "CHI" },
    { value: "kitakyushu", label: "Kitakyushu", code: "KIT" },
    { value: "sakai", label: "Sakai", code: "SAK" },
    { value: "niigata", label: "Niigata", code: "NII" },
    { value: "hamamatsu", label: "Hamamatsu", code: "HAM" },
    { value: "kumamoto", label: "Kumamoto", code: "KUM" },
    { value: "sagamihara", label: "Sagamihara", code: "SAG" },
    { value: "okayama", label: "Okayama", code: "OKA" },
  ],
  "jordan": [
    { value: "amman", label: "Amman", code: "AMM" },
    { value: "zarqa", label: "Zarqa", code: "ZAR" },
    { value: "irbid", label: "Irbid", code: "IRB" },
    { value: "russeifa", label: "Russeifa", code: "RUS" },
    { value: "aqaba", label: "Aqaba", code: "AQA" },
    { value: "madaba", label: "Madaba", code: "MAD" },
    { value: "salt", label: "Salt", code: "SAL" },
    { value: "mafraq", label: "Mafraq", code: "MAF" },
    { value: "jerash", label: "Jerash", code: "JER" },
    { value: "ajloun", label: "Ajloun", code: "AJL" },
    { value: "karak", label: "Karak", code: "KAR" },
    { value: "tafilah", label: "Tafilah", code: "TAF" },
    { value: "maan", label: "Maan", code: "MAA" },
    { value: "sahab", label: "Sahab", code: "SAH" },
    { value: "fuheis", label: "Fuheis", code: "FUH" },
    { value: "saham", label: "Saham", code: "SAH" },
    { value: "ramtha", label: "Ramtha", code: "RAM" },
    { value: "wadi-musa", label: "Wadi Musa", code: "WAD" },
    { value: "petra", label: "Petra", code: "PET" },
    { value: "dead-sea", label: "Dead Sea", code: "DEA" },
  ],
  "kenya": [
    { value: "nairobi", label: "Nairobi", code: "NAI" },
    { value: "mombasa", label: "Mombasa", code: "MOM" },
    { value: "kisumu", label: "Kisumu", code: "KIS" },
    { value: "nakuru", label: "Nakuru", code: "NAK" },
    { value: "eldoret", label: "Eldoret", code: "ELD" },
    { value: "thika", label: "Thika", code: "THI" },
    { value: "malindi", label: "Malindi", code: "MAL" },
    { value: "kitale", label: "Kitale", code: "KIT" },
    { value: "garissa", label: "Garissa", code: "GAR" },
    { value: "kakamega", label: "Kakamega", code: "KAK" },
    { value: "nyeri", label: "Nyeri", code: "NYE" },
    { value: "meru", label: "Meru", code: "MER" },
    { value: "machakos", label: "Machakos", code: "MAC" },
    { value: "lamu", label: "Lamu", code: "LAM" },
    { value: "naivasha", label: "Naivasha", code: "NAI" },
    { value: "kericho", label: "Kericho", code: "KER" },
    { value: "embu", label: "Embu", code: "EMB" },
    { value: "nanyuki", label: "Nanyuki", code: "NAN" },
    { value: "isiolo", label: "Isiolo", code: "ISI" },
    { value: "kilifi", label: "Kilifi", code: "KIL" },
  ],
  "kuwait": [
    { value: "kuwait-city", label: "Kuwait City", code: "KUW" },
    { value: "hawally", label: "Hawally", code: "HAW" },
    { value: "salmiya", label: "Salmiya", code: "SAL" },
    { value: "jahra", label: "Jahra", code: "JAH" },
    { value: "farwaniya", label: "Farwaniya", code: "FAR" },
    { value: "fahaheel", label: "Fahaheel", code: "FAH" },
    { value: "mahboula", label: "Mahboula", code: "MAH" },
    { value: "mangaf", label: "Mangaf", code: "MAN" },
    { value: "sabah-al-salem", label: "Sabah Al Salem", code: "SAB" },
    { value: "jabriya", label: "Jabriya", code: "JAB" },
    { value: "rumaithiya", label: "Rumaithiya", code: "RUM" },
    { value: "abdullah-al-mubarak", label: "Abdullah Al Mubarak", code: "ABD" },
    { value: "ardiya", label: "Ardiya", code: "ARD" },
    { value: "egaila", label: "Egaila", code: "EGA" },
    { value: "messila", label: "Messila", code: "MES" },
    { value: "shuwaikh", label: "Shuwaikh", code: "SHU" },
    { value: "bayan", label: "Bayan", code: "BAY" },
    { value: "surra", label: "Surra", code: "SUR" },
    { value: "sabahiya", label: "Sabahiya", code: "SAB" },
    { value: "fintas", label: "Fintas", code: "FIN" },
  ],
  "lebanon": [
    { value: "beirut", label: "Beirut", code: "BEI" },
    { value: "tripoli", label: "Tripoli", code: "TRI" },
    { value: "sidon", label: "Sidon", code: "SID" },
    { value: "tyre", label: "Tyre", code: "TYR" },
    { value: "jounieh", label: "Jounieh", code: "JOU" },
    { value: "zahle", label: "Zahle", code: "ZAH" },
    { value: "baalbek", label: "Baalbek", code: "BAA" },
    { value: "byblos", label: "Byblos", code: "BYB" },
    { value: "aley", label: "Aley", code: "ALE" },
    { value: "nabatieh", label: "Nabatieh", code: "NAB" },
    { value: "batroun", label: "Batroun", code: "BAT" },
    { value: "zgharta", label: "Zgharta", code: "ZGH" },
    { value: "bint-jbeil", label: "Bint Jbeil", code: "BIN" },
    { value: "halba", label: "Halba", code: "HAL" },
    { value: "anjar", label: "Anjar", code: "ANJ" },
    { value: "jbeil", label: "Jbeil", code: "JBE" },
    { value: "chouf", label: "Chouf", code: "CHO" },
    { value: "metn", label: "Metn", code: "MET" },
    { value: "keserwan", label: "Keserwan", code: "KES" },
    { value: "hermel", label: "Hermel", code: "HER" },
  ],
  "libya": [
    { value: "tripoli", label: "Tripoli", code: "TRI" },
    { value: "benghazi", label: "Benghazi", code: "BEN" },
    { value: "misrata", label: "Misrata", code: "MIS" },
    { value: "bayda", label: "Bayda", code: "BAY" },
    { value: "zawiya", label: "Zawiya", code: "ZAW" },
    { value: "zliten", label: "Zliten", code: "ZLI" },
    { value: "ajdabiya", label: "Ajdabiya", code: "AJD" },
    { value: "sabha", label: "Sabha", code: "SAB" },
    { value: "sirte", label: "Sirte", code: "SIR" },
    { value: "tobruq", label: "Tobruq", code: "TOB" },
    { value: "derna", label: "Derna", code: "DER" },
    { value: "gharyan", label: "Gharyan", code: "GHA" },
    { value: "khoms", label: "Khoms", code: "KHO" },
    { value: "sabratha", label: "Sabratha", code: "SAB" },
    { value: "ubari", label: "Ubari", code: "UBA" },
    { value: "ghat", label: "Ghat", code: "GHA" },
    { value: "nalut", label: "Nalut", code: "NAL" },
    { value: "yafran", label: "Yafran", code: "YAF" },
    { value: "bani-walid", label: "Bani Walid", code: "BAN" },
    { value: "murzuq", label: "Murzuq", code: "MUR" },
  ],
  "malaysia": [
    { value: "kuala-lumpur", label: "Kuala Lumpur", code: "KUA" },
    { value: "george-town", label: "George Town", code: "GEO" },
    { value: "johor-bahru", label: "Johor Bahru", code: "JOH" },
    { value: "ipoh", label: "Ipoh", code: "IPO" },
    { value: "shah-alam", label: "Shah Alam", code: "SHA" },
    { value: "petaling-jaya", label: "Petaling Jaya", code: "PET" },
    { value: "malacca-city", label: "Malacca City", code: "MAL" },
    { value: "kota-kinabalu", label: "Kota Kinabalu", code: "KOT" },
    { value: "kuching", label: "Kuching", code: "KUC" },
    { value: "alor-setar", label: "Alor Setar", code: "ALO" },
    { value: "kuantan", label: "Kuantan", code: "KUA" },
    { value: "kota-bharu", label: "Kota Bharu", code: "KOT" },
    { value: "seremban", label: "Seremban", code: "SER" },
    { value: "subang-jaya", label: "Subang Jaya", code: "SUB" },
    { value: "klang", label: "Klang", code: "KLA" },
    { value: "miri", label: "Miri", code: "MIR" },
    { value: "sandakan", label: "Sandakan", code: "SAN" },
    { value: "tawau", label: "Tawau", code: "TAW" },
    { value: "taiping", label: "Taiping", code: "TAI" },
    { value: "muar", label: "Muar", code: "MUA" },
  ],
  "mexico": [
    { value: "mexico-city", label: "Mexico City", code: "MEX" },
    { value: "guadalajara", label: "Guadalajara", code: "GUA" },
    { value: "monterrey", label: "Monterrey", code: "MON" },
    { value: "puebla", label: "Puebla", code: "PUE" },
    { value: "tijuana", label: "Tijuana", code: "TIJ" },
    { value: "leon", label: "Leon", code: "LEO" },
    { value: "juarez", label: "Juarez", code: "JUA" },
    { value: "zapopan", label: "Zapopan", code: "ZAP" },
    { value: "merida", label: "Merida", code: "MER" },
    { value: "cancun", label: "Cancun", code: "CAN" },
    { value: "aguascalientes", label: "Aguascalientes", code: "AGU" },
    { value: "queretaro", label: "Queretaro", code: "QUE" },
    { value: "san-luis-potosi", label: "San Luis Potosi", code: "SAN" },
    { value: "mexicali", label: "Mexicali", code: "MEX" },
    { value: "hermosillo", label: "Hermosillo", code: "HER" },
    { value: "saltillo", label: "Saltillo", code: "SAL" },
    { value: "culiacan", label: "Culiacan", code: "CUL" },
    { value: "morelia", label: "Morelia", code: "MOR" },
    { value: "chihuahua", label: "Chihuahua", code: "CHI" },
    { value: "toluca", label: "Toluca", code: "TOL" },
  ],
  "morocco": [
    { value: "casablanca", label: "Casablanca", code: "CAS" },
    { value: "rabat", label: "Rabat", code: "RAB" },
    { value: "fes", label: "Fes", code: "FES" },
    { value: "marrakech", label: "Marrakech", code: "MAR" },
    { value: "tangier", label: "Tangier", code: "TAN" },
    { value: "agadir", label: "Agadir", code: "AGA" },
    { value: "meknes", label: "Meknes", code: "MEK" },
    { value: "oujda", label: "Oujda", code: "OUJ" },
    { value: "kenitra", label: "Kenitra", code: "KEN" },
    { value: "tetouan", label: "Tetouan", code: "TET" },
    { value: "safi", label: "Safi", code: "SAF" },
    { value: "mohammedia", label: "Mohammedia", code: "MOH" },
    { value: "el-jadida", label: "El Jadida", code: "ELJ" },
    { value: "nador", label: "Nador", code: "NAD" },
    { value: "beni-mellal", label: "Beni Mellal", code: "BEN" },
    { value: "khouribga", label: "Khouribga", code: "KHO" },
    { value: "settat", label: "Settat", code: "SET" },
    { value: "larache", label: "Larache", code: "LAR" },
    { value: "khemisset", label: "Khemisset", code: "KHE" },
    { value: "guelmim", label: "Guelmim", code: "GUE" },
  ],
  "netherlands": [
    { value: "amsterdam", label: "Amsterdam", code: "AMS" },
    { value: "rotterdam", label: "Rotterdam", code: "ROT" },
    { value: "the-hague", label: "The Hague", code: "THE" },
    { value: "utrecht", label: "Utrecht", code: "UTR" },
    { value: "eindhoven", label: "Eindhoven", code: "EIN" },
    { value: "groningen", label: "Groningen", code: "GRO" },
    { value: "tilburg", label: "Tilburg", code: "TIL" },
    { value: "almere", label: "Almere", code: "ALM" },
    { value: "breda", label: "Breda", code: "BRE" },
    { value: "nijmegen", label: "Nijmegen", code: "NIJ" },
    { value: "apeldoorn", label: "Apeldoorn", code: "APE" },
    { value: "haarlem", label: "Haarlem", code: "HAA" },
    { value: "arnhem", label: "Arnhem", code: "ARN" },
    { value: "enschede", label: "Enschede", code: "ENS" },
    { value: "amersfoort", label: "Amersfoort", code: "AME" },
    { value: "zaanstad", label: "Zaanstad", code: "ZAA" },
    { value: "haarlemmermeer", label: "Haarlemmermeer", code: "HAA" },
    { value: "s-hertogenbosch", label: "s-Hertogenbosch", code: "SHE" },
    { value: "zwolle", label: "Zwolle", code: "ZWO" },
    { value: "leiden", label: "Leiden", code: "LEI" },
  ],
  "new-zealand": [
    { value: "auckland", label: "Auckland", code: "AUC" },
    { value: "wellington", label: "Wellington", code: "WEL" },
    { value: "christchurch", label: "Christchurch", code: "CHR" },
    { value: "hamilton", label: "Hamilton", code: "HAM" },
    { value: "tauranga", label: "Tauranga", code: "TAU" },
    { value: "dunedin", label: "Dunedin", code: "DUN" },
    { value: "palmerston-north", label: "Palmerston North", code: "PAL" },
    { value: "napier", label: "Napier", code: "NAP" },
    { value: "nelson", label: "Nelson", code: "NEL" },
    { value: "rotorua", label: "Rotorua", code: "ROT" },
    { value: "new-plymouth", label: "New Plymouth", code: "NEW" },
    { value: "whangarei", label: "Whangarei", code: "WHA" },
    { value: "invercargill", label: "Invercargill", code: "INV" },
    { value: "whanganui", label: "Whanganui", code: "WHA" },
    { value: "gisborne", label: "Gisborne", code: "GIS" },
    { value: "queenstown", label: "Queenstown", code: "QUE" },
    { value: "pukekohe", label: "Pukekohe", code: "PUK" },
    { value: "timaru", label: "Timaru", code: "TIM" },
    { value: "blenheim", label: "Blenheim", code: "BLE" },
    { value: "taupo", label: "Taupo", code: "TAU" },
  ],
  "nigeria": [
    { value: "lagos", label: "Lagos", code: "LAG" },
    { value: "abuja", label: "Abuja", code: "ABU" },
    { value: "kano", label: "Kano", code: "KAN" },
    { value: "ibadan", label: "Ibadan", code: "IBA" },
    { value: "port-harcourt", label: "Port Harcourt", code: "POR" },
    { value: "benin-city", label: "Benin City", code: "BEN" },
    { value: "kaduna", label: "Kaduna", code: "KAD" },
    { value: "maiduguri", label: "Maiduguri", code: "MAI" },
    { value: "ilorin", label: "Ilorin", code: "ILO" },
    { value: "enugu", label: "Enugu", code: "ENU" },
    { value: "abeokuta", label: "Abeokuta", code: "ABE" },
    { value: "onitsha", label: "Onitsha", code: "ONI" },
    { value: "warri", label: "Warri", code: "WAR" },
    { value: "jos", label: "Jos", code: "JOS" },
    { value: "aba", label: "Aba", code: "ABA" },
    { value: "calabar", label: "Calabar", code: "CAL" },
    { value: "uyo", label: "Uyo", code: "UYO" },
    { value: "sokoto", label: "Sokoto", code: "SOK" },
    { value: "owerri", label: "Owerri", code: "OWE" },
    { value: "zaria", label: "Zaria", code: "ZAR" },
  ],
  "norway": [
    { value: "oslo", label: "Oslo", code: "OSL" },
    { value: "bergen", label: "Bergen", code: "BER" },
    { value: "trondheim", label: "Trondheim", code: "TRO" },
    { value: "stavanger", label: "Stavanger", code: "STA" },
    { value: "drammen", label: "Drammen", code: "DRA" },
    { value: "fredrikstad", label: "Fredrikstad", code: "FRE" },
    { value: "kristiansand", label: "Kristiansand", code: "KRI" },
    { value: "sandnes", label: "Sandnes", code: "SAN" },
    { value: "tromso", label: "Tromso", code: "TRO" },
    { value: "sarpsborg", label: "Sarpsborg", code: "SAR" },
    { value: "skien", label: "Skien", code: "SKI" },
    { value: "alesund", label: "Alesund", code: "ALE" },
    { value: "tonsberg", label: "Tonsberg", code: "TON" },
    { value: "moss", label: "Moss", code: "MOS" },
    { value: "haugesund", label: "Haugesund", code: "HAU" },
    { value: "arendal", label: "Arendal", code: "ARE" },
    { value: "bodo", label: "Bodo", code: "BOD" },
    { value: "hamar", label: "Hamar", code: "HAM" },
    { value: "larvik", label: "Larvik", code: "LAR" },
    { value: "halden", label: "Halden", code: "HAL" },
  ],
  "oman": [
    { value: "muscat", label: "Muscat", code: "MUS" },
    { value: "salalah", label: "Salalah", code: "SAL" },
    { value: "sohar", label: "Sohar", code: "SOH" },
    { value: "nizwa", label: "Nizwa", code: "NIZ" },
    { value: "sur", label: "Sur", code: "SUR" },
    { value: "ibri", label: "Ibri", code: "IBR" },
    { value: "barka", label: "Barka", code: "BAR" },
    { value: "rustaq", label: "Rustaq", code: "RUS" },
    { value: "seeb", label: "Seeb", code: "SEE" },
    { value: "saham", label: "Saham", code: "SAH" },
    { value: "khasab", label: "Khasab", code: "KHA" },
    { value: "bahla", label: "Bahla", code: "BAH" },
    { value: "ibra", label: "Ibra", code: "IBR" },
    { value: "buraimi", label: "Buraimi", code: "BUR" },
    { value: "duqm", label: "Duqm", code: "DUQ" },
    { value: "adam", label: "Adam", code: "ADA" },
    { value: "sinaw", label: "Sinaw", code: "SIN" },
    { value: "al-mudhaibi", label: "Al Mudhaibi", code: "ALM" },
    { value: "quriyat", label: "Quriyat", code: "QUR" },
    { value: "al-suwaiq", label: "Al Suwaiq", code: "ALS" },
  ],
  "pakistan": [
    { value: "lahore", label: "Lahore", code: "LAH" },
    { value: "karachi", label: "Karachi", code: "KAR" },
    { value: "islamabad", label: "Islamabad", code: "ISL" },
    { value: "rawalpindi", label: "Rawalpindi", code: "RAW" },
    { value: "faisalabad", label: "Faisalabad", code: "FAI" },
    { value: "multan", label: "Multan", code: "MUL" },
    { value: "peshawar", label: "Peshawar", code: "PES" },
    { value: "quetta", label: "Quetta", code: "QUE" },
    { value: "sialkot", label: "Sialkot", code: "SIA" },
    { value: "gujranwala", label: "Gujranwala", code: "GUJ" },
    { value: "hyderabad", label: "Hyderabad", code: "HYD" },
    { value: "bahawalpur", label: "Bahawalpur", code: "BAH" },
    { value: "sargodha", label: "Sargodha", code: "SAR" },
    { value: "sukkur", label: "Sukkur", code: "SUK" },
    { value: "larkana", label: "Larkana", code: "LAR" },
    { value: "sheikhupura", label: "Sheikhupura", code: "SHE" },
    { value: "jhang", label: "Jhang", code: "JHA" },
    { value: "rahim-yar-khan", label: "Rahim Yar Khan", code: "RAH" },
    { value: "gujrat", label: "Gujrat", code: "GUJ" },
    { value: "mardan", label: "Mardan", code: "MAR" },
    { value: "abbottabad", label: "Abbottabad", code: "ABB" },
    { value: "mirpur", label: "Mirpur", code: "MIR" },
    { value: "gwadar", label: "Gwadar", code: "GWA" },
    { value: "okara", label: "Okara", code: "OKA" },
  ],
  "philippines": [
    { value: "manila", label: "Manila", code: "MAN" },
    { value: "quezon-city", label: "Quezon City", code: "QUE" },
    { value: "davao", label: "Davao", code: "DAV" },
    { value: "cebu-city", label: "Cebu City", code: "CEB" },
    { value: "zamboanga", label: "Zamboanga", code: "ZAM" },
    { value: "taguig", label: "Taguig", code: "TAG" },
    { value: "pasig", label: "Pasig", code: "PAS" },
    { value: "cagayan-de-oro", label: "Cagayan de Oro", code: "CAG" },
    { value: "paranaque", label: "Paranaque", code: "PAR" },
    { value: "dasmarinas", label: "Dasmarinas", code: "DAS" },
    { value: "general-santos", label: "General Santos", code: "GEN" },
    { value: "bacolod", label: "Bacolod", code: "BAC" },
    { value: "iloilo-city", label: "Iloilo City", code: "ILO" },
    { value: "makati", label: "Makati", code: "MAK" },
    { value: "mandaluyong", label: "Mandaluyong", code: "MAN" },
    { value: "baguio", label: "Baguio", code: "BAG" },
    { value: "antipolo", label: "Antipolo", code: "ANT" },
    { value: "calamba", label: "Calamba", code: "CAL" },
    { value: "angeles", label: "Angeles", code: "ANG" },
    { value: "butuan", label: "Butuan", code: "BUT" },
  ],
  "poland": [
    { value: "warsaw", label: "Warsaw", code: "WAR" },
    { value: "krakow", label: "Krakow", code: "KRA" },
    { value: "lodz", label: "Lodz", code: "LOD" },
    { value: "wroclaw", label: "Wroclaw", code: "WRO" },
    { value: "poznan", label: "Poznan", code: "POZ" },
    { value: "gdansk", label: "Gdansk", code: "GDA" },
    { value: "szczecin", label: "Szczecin", code: "SZC" },
    { value: "bydgoszcz", label: "Bydgoszcz", code: "BYD" },
    { value: "lublin", label: "Lublin", code: "LUB" },
    { value: "bialystok", label: "Bialystok", code: "BIA" },
    { value: "katowice", label: "Katowice", code: "KAT" },
    { value: "gdynia", label: "Gdynia", code: "GDY" },
    { value: "czestochowa", label: "Czestochowa", code: "CZE" },
    { value: "radom", label: "Radom", code: "RAD" },
    { value: "torun", label: "Torun", code: "TOR" },
    { value: "sosnowiec", label: "Sosnowiec", code: "SOS" },
    { value: "kielce", label: "Kielce", code: "KIE" },
    { value: "rzeszow", label: "Rzeszow", code: "RZE" },
    { value: "gliwice", label: "Gliwice", code: "GLI" },
    { value: "olsztyn", label: "Olsztyn", code: "OLS" },
  ],
  "portugal": [
    { value: "lisbon", label: "Lisbon", code: "LIS" },
    { value: "porto", label: "Porto", code: "POR" },
    { value: "vila-nova-de-gaia", label: "Vila Nova de Gaia", code: "VIL" },
    { value: "amadora", label: "Amadora", code: "AMA" },
    { value: "braga", label: "Braga", code: "BRA" },
    { value: "funchal", label: "Funchal", code: "FUN" },
    { value: "coimbra", label: "Coimbra", code: "COI" },
    { value: "setubal", label: "Setubal", code: "SET" },
    { value: "almada", label: "Almada", code: "ALM" },
    { value: "agualva-cacem", label: "Agualva-Cacem", code: "AGU" },
    { value: "queluz", label: "Queluz", code: "QUE" },
    { value: "faro", label: "Faro", code: "FAR" },
    { value: "evora", label: "Evora", code: "EVO" },
    { value: "aveiro", label: "Aveiro", code: "AVE" },
    { value: "leiria", label: "Leiria", code: "LEI" },
    { value: "guimaraes", label: "Guimaraes", code: "GUI" },
    { value: "viseu", label: "Viseu", code: "VIS" },
    { value: "ponta-delgada", label: "Ponta Delgada", code: "PON" },
    { value: "portimao", label: "Portimao", code: "POR" },
    { value: "cascais", label: "Cascais", code: "CAS" },
  ],
  "qatar": [
    { value: "doha", label: "Doha", code: "DOH" },
    { value: "al-rayyan", label: "Al Rayyan", code: "ALR" },
    { value: "al-wakrah", label: "Al Wakrah", code: "ALW" },
    { value: "al-khor", label: "Al Khor", code: "ALK" },
    { value: "umm-salal", label: "Umm Salal", code: "UMM" },
    { value: "al-daayen", label: "Al Daayen", code: "ALD" },
    { value: "mesaieed", label: "Mesaieed", code: "MES" },
    { value: "dukhan", label: "Dukhan", code: "DUK" },
    { value: "lusail", label: "Lusail", code: "LUS" },
    { value: "the-pearl", label: "The Pearl", code: "THE" },
    { value: "west-bay", label: "West Bay", code: "WES" },
    { value: "al-thakhira", label: "Al Thakhira", code: "ALT" },
    { value: "madinat-ash-shamal", label: "Madinat ash Shamal", code: "MAD" },
    { value: "abu-samra", label: "Abu Samra", code: "ABU" },
    { value: "al-ruwais", label: "Al Ruwais", code: "ALR" },
    { value: "simaisma", label: "Simaisma", code: "SIM" },
    { value: "al-wukair", label: "Al Wukair", code: "ALW" },
    { value: "education-city", label: "Education City", code: "EDU" },
    { value: "msheireb", label: "Msheireb", code: "MSH" },
    { value: "katara", label: "Katara", code: "KAT" },
  ],
  "romania": [
    { value: "bucharest", label: "Bucharest", code: "BUC" },
    { value: "cluj-napoca", label: "Cluj-Napoca", code: "CLU" },
    { value: "timisoara", label: "Timisoara", code: "TIM" },
    { value: "iasi", label: "Iasi", code: "IAS" },
    { value: "constanta", label: "Constanta", code: "CON" },
    { value: "craiova", label: "Craiova", code: "CRA" },
    { value: "brasov", label: "Brasov", code: "BRA" },
    { value: "galati", label: "Galati", code: "GAL" },
    { value: "ploiesti", label: "Ploiesti", code: "PLO" },
    { value: "oradea", label: "Oradea", code: "ORA" },
    { value: "braila", label: "Braila", code: "BRA" },
    { value: "arad", label: "Arad", code: "ARA" },
    { value: "pitesti", label: "Pitesti", code: "PIT" },
    { value: "sibiu", label: "Sibiu", code: "SIB" },
    { value: "bacau", label: "Bacau", code: "BAC" },
    { value: "targu-mures", label: "Targu Mures", code: "TAR" },
    { value: "baia-mare", label: "Baia Mare", code: "BAI" },
    { value: "buzau", label: "Buzau", code: "BUZ" },
    { value: "botosani", label: "Botosani", code: "BOT" },
    { value: "satu-mare", label: "Satu Mare", code: "SAT" },
  ],
  "saudi-arabia": [
    { value: "riyadh", label: "Riyadh", code: "RIY" },
    { value: "jeddah", label: "Jeddah", code: "JED" },
    { value: "mecca", label: "Mecca", code: "MEC" },
    { value: "medina", label: "Medina", code: "MED" },
    { value: "dammam", label: "Dammam", code: "DAM" },
    { value: "khobar", label: "Khobar", code: "KHO" },
    { value: "taif", label: "Taif", code: "TAI" },
    { value: "tabuk", label: "Tabuk", code: "TAB" },
    { value: "buraidah", label: "Buraidah", code: "BUR" },
    { value: "khamis-mushait", label: "Khamis Mushait", code: "KHA" },
    { value: "abha", label: "Abha", code: "ABH" },
    { value: "jubail", label: "Jubail", code: "JUB" },
    { value: "najran", label: "Najran", code: "NAJ" },
    { value: "yanbu", label: "Yanbu", code: "YAN" },
    { value: "al-ahsa", label: "Al Ahsa", code: "ALA" },
    { value: "hail", label: "Hail", code: "HAI" },
    { value: "jizan", label: "Jizan", code: "JIZ" },
    { value: "qatif", label: "Qatif", code: "QAT" },
    { value: "arar", label: "Arar", code: "ARA" },
    { value: "sakaka", label: "Sakaka", code: "SAK" },
  ],
  "singapore": [
    { value: "marina-bay", label: "Marina Bay", code: "MAR" },
    { value: "orchard", label: "Orchard", code: "ORC" },
    { value: "bugis", label: "Bugis", code: "BUG" },
    { value: "chinatown", label: "Chinatown", code: "CHI" },
    { value: "little-india", label: "Little India", code: "LIT" },
    { value: "kampong-glam", label: "Kampong Glam", code: "KAM" },
    { value: "tampines", label: "Tampines", code: "TAM" },
    { value: "jurong-east", label: "Jurong East", code: "JUR" },
    { value: "woodlands", label: "Woodlands", code: "WOO" },
    { value: "yishun", label: "Yishun", code: "YIS" },
    { value: "bedok", label: "Bedok", code: "BED" },
    { value: "clementi", label: "Clementi", code: "CLE" },
    { value: "ang-mo-kio", label: "Ang Mo Kio", code: "ANG" },
    { value: "toa-payoh", label: "Toa Payoh", code: "TOA" },
    { value: "queenstown", label: "Queenstown", code: "QUE" },
    { value: "punggol", label: "Punggol", code: "PUN" },
    { value: "sengkang", label: "Sengkang", code: "SEN" },
    { value: "bishan", label: "Bishan", code: "BIS" },
    { value: "pasir-ris", label: "Pasir Ris", code: "PAS" },
    { value: "holland-village", label: "Holland Village", code: "HOL" },
  ],
  "south-africa": [
    { value: "johannesburg", label: "Johannesburg", code: "JOH" },
    { value: "cape-town", label: "Cape Town", code: "CAP" },
    { value: "durban", label: "Durban", code: "DUR" },
    { value: "pretoria", label: "Pretoria", code: "PRE" },
    { value: "port-elizabeth", label: "Port Elizabeth", code: "POR" },
    { value: "bloemfontein", label: "Bloemfontein", code: "BLO" },
    { value: "east-london", label: "East London", code: "EAS" },
    { value: "pietermaritzburg", label: "Pietermaritzburg", code: "PIE" },
    { value: "polokwane", label: "Polokwane", code: "POL" },
    { value: "nelspruit", label: "Nelspruit", code: "NEL" },
    { value: "kimberley", label: "Kimberley", code: "KIM" },
    { value: "rustenburg", label: "Rustenburg", code: "RUS" },
    { value: "soweto", label: "Soweto", code: "SOW" },
    { value: "centurion", label: "Centurion", code: "CEN" },
    { value: "sandton", label: "Sandton", code: "SAN" },
    { value: "stellenbosch", label: "Stellenbosch", code: "STE" },
    { value: "george", label: "George", code: "GEO" },
    { value: "midrand", label: "Midrand", code: "MID" },
    { value: "richards-bay", label: "Richards Bay", code: "RIC" },
    { value: "witbank", label: "Witbank", code: "WIT" },
  ],
  "south-korea": [
    { value: "seoul", label: "Seoul", code: "SEO" },
    { value: "busan", label: "Busan", code: "BUS" },
    { value: "incheon", label: "Incheon", code: "INC" },
    { value: "daegu", label: "Daegu", code: "DAE" },
    { value: "daejeon", label: "Daejeon", code: "DAE" },
    { value: "gwangju", label: "Gwangju", code: "GWA" },
    { value: "suwon", label: "Suwon", code: "SUW" },
    { value: "ulsan", label: "Ulsan", code: "ULS" },
    { value: "changwon", label: "Changwon", code: "CHA" },
    { value: "goyang", label: "Goyang", code: "GOY" },
    { value: "yongin", label: "Yongin", code: "YON" },
    { value: "seongnam", label: "Seongnam", code: "SEO" },
    { value: "bucheon", label: "Bucheon", code: "BUC" },
    { value: "ansan", label: "Ansan", code: "ANS" },
    { value: "cheongju", label: "Cheongju", code: "CHE" },
    { value: "jeonju", label: "Jeonju", code: "JEO" },
    { value: "cheonan", label: "Cheonan", code: "CHE" },
    { value: "namyangju", label: "Namyangju", code: "NAM" },
    { value: "hwaseong", label: "Hwaseong", code: "HWA" },
    { value: "pohang", label: "Pohang", code: "POH" },
  ],
  "spain": [
    { value: "madrid", label: "Madrid", code: "MAD" },
    { value: "barcelona", label: "Barcelona", code: "BAR" },
    { value: "valencia", label: "Valencia", code: "VAL" },
    { value: "seville", label: "Seville", code: "SEV" },
    { value: "zaragoza", label: "Zaragoza", code: "ZAR" },
    { value: "malaga", label: "Malaga", code: "MAL" },
    { value: "murcia", label: "Murcia", code: "MUR" },
    { value: "palma", label: "Palma", code: "PAL" },
    { value: "las-palmas", label: "Las Palmas", code: "LAS" },
    { value: "bilbao", label: "Bilbao", code: "BIL" },
    { value: "alicante", label: "Alicante", code: "ALI" },
    { value: "cordoba", label: "Cordoba", code: "COR" },
    { value: "valladolid", label: "Valladolid", code: "VAL" },
    { value: "vigo", label: "Vigo", code: "VIG" },
    { value: "gijon", label: "Gijon", code: "GIJ" },
    { value: "hospitalet", label: "Hospitalet", code: "HOS" },
    { value: "vitoria", label: "Vitoria", code: "VIT" },
    { value: "a-coruna", label: "A Coruna", code: "ACO" },
    { value: "granada", label: "Granada", code: "GRA" },
    { value: "elche", label: "Elche", code: "ELC" },
  ],
  "sri-lanka": [
    { value: "colombo", label: "Colombo", code: "COL" },
    { value: "kandy", label: "Kandy", code: "KAN" },
    { value: "galle", label: "Galle", code: "GAL" },
    { value: "jaffna", label: "Jaffna", code: "JAF" },
    { value: "negombo", label: "Negombo", code: "NEG" },
    { value: "trincomalee", label: "Trincomalee", code: "TRI" },
    { value: "batticaloa", label: "Batticaloa", code: "BAT" },
    { value: "matara", label: "Matara", code: "MAT" },
    { value: "anuradhapura", label: "Anuradhapura", code: "ANU" },
    { value: "ratnapura", label: "Ratnapura", code: "RAT" },
    { value: "kurunegala", label: "Kurunegala", code: "KUR" },
    { value: "badulla", label: "Badulla", code: "BAD" },
    { value: "nuwara-eliya", label: "Nuwara Eliya", code: "NUW" },
    { value: "kalutara", label: "Kalutara", code: "KAL" },
    { value: "moratuwa", label: "Moratuwa", code: "MOR" },
    { value: "dehiwala", label: "Dehiwala", code: "DEH" },
    { value: "mount-lavinia", label: "Mount Lavinia", code: "MOU" },
    { value: "hambantota", label: "Hambantota", code: "HAM" },
    { value: "chilaw", label: "Chilaw", code: "CHI" },
    { value: "puttalam", label: "Puttalam", code: "PUT" },
  ],
  "sweden": [
    { value: "stockholm", label: "Stockholm", code: "STO" },
    { value: "gothenburg", label: "Gothenburg", code: "GOT" },
    { value: "malmo", label: "Malmo", code: "MAL" },
    { value: "uppsala", label: "Uppsala", code: "UPP" },
    { value: "vasteras", label: "Vasteras", code: "VAS" },
    { value: "orebro", label: "Orebro", code: "ORE" },
    { value: "linkoping", label: "Linkoping", code: "LIN" },
    { value: "helsingborg", label: "Helsingborg", code: "HEL" },
    { value: "jonkoping", label: "Jonkoping", code: "JON" },
    { value: "norrkoping", label: "Norrkoping", code: "NOR" },
    { value: "lund", label: "Lund", code: "LUN" },
    { value: "umea", label: "Umea", code: "UME" },
    { value: "gavle", label: "Gavle", code: "GAV" },
    { value: "boras", label: "Boras", code: "BOR" },
    { value: "sodertalje", label: "Sodertalje", code: "SOD" },
    { value: "eskilstuna", label: "Eskilstuna", code: "ESK" },
    { value: "karlstad", label: "Karlstad", code: "KAR" },
    { value: "taby", label: "Taby", code: "TAB" },
    { value: "vaxjo", label: "Vaxjo", code: "VAX" },
    { value: "halmstad", label: "Halmstad", code: "HAL" },
  ],
  "switzerland": [
    { value: "zurich", label: "Zurich", code: "ZUR" },
    { value: "geneva", label: "Geneva", code: "GEN" },
    { value: "basel", label: "Basel", code: "BAS" },
    { value: "lausanne", label: "Lausanne", code: "LAU" },
    { value: "bern", label: "Bern", code: "BER" },
    { value: "winterthur", label: "Winterthur", code: "WIN" },
    { value: "lucerne", label: "Lucerne", code: "LUC" },
    { value: "st-gallen", label: "St Gallen", code: "STG" },
    { value: "lugano", label: "Lugano", code: "LUG" },
    { value: "biel", label: "Biel", code: "BIE" },
    { value: "thun", label: "Thun", code: "THU" },
    { value: "koniz", label: "Koniz", code: "KON" },
    { value: "la-chaux-de-fonds", label: "La Chaux-de-Fonds", code: "LAC" },
    { value: "schaffhausen", label: "Schaffhausen", code: "SCH" },
    { value: "fribourg", label: "Fribourg", code: "FRI" },
    { value: "chur", label: "Chur", code: "CHU" },
    { value: "neuchatel", label: "Neuchatel", code: "NEU" },
    { value: "vernier", label: "Vernier", code: "VER" },
    { value: "uster", label: "Uster", code: "UST" },
    { value: "sion", label: "Sion", code: "SIO" },
  ],
  "taiwan": [
    { value: "taipei", label: "Taipei", code: "TAI" },
    { value: "kaohsiung", label: "Kaohsiung", code: "KAO" },
    { value: "taichung", label: "Taichung", code: "TAI" },
    { value: "tainan", label: "Tainan", code: "TAI" },
    { value: "hsinchu", label: "Hsinchu", code: "HSI" },
    { value: "taoyuan", label: "Taoyuan", code: "TAO" },
    { value: "keelung", label: "Keelung", code: "KEE" },
    { value: "chiayi", label: "Chiayi", code: "CHI" },
    { value: "changhua", label: "Changhua", code: "CHA" },
    { value: "pingtung", label: "Pingtung", code: "PIN" },
    { value: "yilan", label: "Yilan", code: "YIL" },
    { value: "hualien", label: "Hualien", code: "HUA" },
    { value: "taitung", label: "Taitung", code: "TAI" },
    { value: "miaoli", label: "Miaoli", code: "MIA" },
    { value: "nantou", label: "Nantou", code: "NAN" },
    { value: "yunlin", label: "Yunlin", code: "YUN" },
    { value: "penghu", label: "Penghu", code: "PEN" },
    { value: "kinmen", label: "Kinmen", code: "KIN" },
    { value: "new-taipei", label: "New Taipei", code: "NEW" },
    { value: "zhongli", label: "Zhongli", code: "ZHO" },
  ],
  "thailand": [
    { value: "bangkok", label: "Bangkok", code: "BAN" },
    { value: "chiang-mai", label: "Chiang Mai", code: "CHI" },
    { value: "pattaya", label: "Pattaya", code: "PAT" },
    { value: "phuket", label: "Phuket", code: "PHU" },
    { value: "hat-yai", label: "Hat Yai", code: "HAT" },
    { value: "nakhon-ratchasima", label: "Nakhon Ratchasima", code: "NAK" },
    { value: "udon-thani", label: "Udon Thani", code: "UDO" },
    { value: "khon-kaen", label: "Khon Kaen", code: "KHO" },
    { value: "chiang-rai", label: "Chiang Rai", code: "CHI" },
    { value: "surat-thani", label: "Surat Thani", code: "SUR" },
    { value: "nakhon-si-thammarat", label: "Nakhon Si Thammarat", code: "NAK" },
    { value: "nonthaburi", label: "Nonthaburi", code: "NON" },
    { value: "pak-kret", label: "Pak Kret", code: "PAK" },
    { value: "rayong", label: "Rayong", code: "RAY" },
    { value: "hua-hin", label: "Hua Hin", code: "HUA" },
    { value: "ayutthaya", label: "Ayutthaya", code: "AYU" },
    { value: "krabi", label: "Krabi", code: "KRA" },
    { value: "samut-prakan", label: "Samut Prakan", code: "SAM" },
    { value: "lampang", label: "Lampang", code: "LAM" },
    { value: "nakhon-sawan", label: "Nakhon Sawan", code: "NAK" },
  ],
  "tunisia": [
    { value: "tunis", label: "Tunis", code: "TUN" },
    { value: "sfax", label: "Sfax", code: "SFA" },
    { value: "sousse", label: "Sousse", code: "SOU" },
    { value: "kairouan", label: "Kairouan", code: "KAI" },
    { value: "bizerte", label: "Bizerte", code: "BIZ" },
    { value: "gabes", label: "Gabes", code: "GAB" },
    { value: "ariana", label: "Ariana", code: "ARI" },
    { value: "gafsa", label: "Gafsa", code: "GAF" },
    { value: "monastir", label: "Monastir", code: "MON" },
    { value: "ben-arous", label: "Ben Arous", code: "BEN" },
    { value: "kasserine", label: "Kasserine", code: "KAS" },
    { value: "medenine", label: "Medenine", code: "MED" },
    { value: "nabeul", label: "Nabeul", code: "NAB" },
    { value: "tataouine", label: "Tataouine", code: "TAT" },
    { value: "beja", label: "Beja", code: "BEJ" },
    { value: "jendouba", label: "Jendouba", code: "JEN" },
    { value: "mahdia", label: "Mahdia", code: "MAH" },
    { value: "sidi-bouzid", label: "Sidi Bouzid", code: "SID" },
    { value: "tozeur", label: "Tozeur", code: "TOZ" },
    { value: "el-kef", label: "El Kef", code: "ELK" },
  ],
  "turkey": [
    { value: "istanbul", label: "Istanbul", code: "IST" },
    { value: "ankara", label: "Ankara", code: "ANK" },
    { value: "izmir", label: "Izmir", code: "IZM" },
    { value: "bursa", label: "Bursa", code: "BUR" },
    { value: "antalya", label: "Antalya", code: "ANT" },
    { value: "adana", label: "Adana", code: "ADA" },
    { value: "gaziantep", label: "Gaziantep", code: "GAZ" },
    { value: "konya", label: "Konya", code: "KON" },
    { value: "mersin", label: "Mersin", code: "MER" },
    { value: "diyarbakir", label: "Diyarbakir", code: "DIY" },
    { value: "kayseri", label: "Kayseri", code: "KAY" },
    { value: "eskisehir", label: "Eskisehir", code: "ESK" },
    { value: "samsun", label: "Samsun", code: "SAM" },
    { value: "denizli", label: "Denizli", code: "DEN" },
    { value: "sanliurfa", label: "Sanliurfa", code: "SAN" },
    { value: "malatya", label: "Malatya", code: "MAL" },
    { value: "erzurum", label: "Erzurum", code: "ERZ" },
    { value: "van", label: "Van", code: "VAN" },
    { value: "batman", label: "Batman", code: "BAT" },
    { value: "elazig", label: "Elazig", code: "ELA" },
  ],
  "uae": [
    { value: "dubai", label: "Dubai", code: "DUB" },
    { value: "abu-dhabi", label: "Abu Dhabi", code: "ABU" },
    { value: "sharjah", label: "Sharjah", code: "SHA" },
    { value: "ajman", label: "Ajman", code: "AJM" },
    { value: "ras-al-khaimah", label: "Ras Al Khaimah", code: "RAS" },
    { value: "fujairah", label: "Fujairah", code: "FUJ" },
    { value: "al-ain", label: "Al Ain", code: "ALA" },
    { value: "umm-al-quwain", label: "Umm Al Quwain", code: "UMM" },
    { value: "dibba", label: "Dibba", code: "DIB" },
    { value: "kalba", label: "Kalba", code: "KAL" },
    { value: "madinat-zayed", label: "Madinat Zayed", code: "MAD" },
    { value: "ruwais", label: "Ruwais", code: "RUW" },
    { value: "liwa", label: "Liwa", code: "LIW" },
    { value: "masdar-city", label: "Masdar City", code: "MAS" },
    { value: "palm-jumeirah", label: "Palm Jumeirah", code: "PAL" },
    { value: "jebel-ali", label: "Jebel Ali", code: "JEB" },
    { value: "khalifa-city", label: "Khalifa City", code: "KHA" },
    { value: "mussafah", label: "Mussafah", code: "MUS" },
    { value: "ghayathi", label: "Ghayathi", code: "GHA" },
    { value: "hatta", label: "Hatta", code: "HAT" },
  ],
  "ukraine": [
    { value: "kyiv", label: "Kyiv", code: "KYI" },
    { value: "kharkiv", label: "Kharkiv", code: "KHA" },
    { value: "odesa", label: "Odesa", code: "ODE" },
    { value: "dnipro", label: "Dnipro", code: "DNI" },
    { value: "lviv", label: "Lviv", code: "LVI" },
    { value: "zaporizhzhia", label: "Zaporizhzhia", code: "ZAP" },
    { value: "kryvyi-rih", label: "Kryvyi Rih", code: "KRY" },
    { value: "mykolaiv", label: "Mykolaiv", code: "MYK" },
    { value: "mariupol", label: "Mariupol", code: "MAR" },
    { value: "vinnytsia", label: "Vinnytsia", code: "VIN" },
    { value: "kherson", label: "Kherson", code: "KHE" },
    { value: "poltava", label: "Poltava", code: "POL" },
    { value: "chernihiv", label: "Chernihiv", code: "CHE" },
    { value: "cherkasy", label: "Cherkasy", code: "CHE" },
    { value: "zhytomyr", label: "Zhytomyr", code: "ZHY" },
    { value: "sumy", label: "Sumy", code: "SUM" },
    { value: "rivne", label: "Rivne", code: "RIV" },
    { value: "ivano-frankivsk", label: "Ivano-Frankivsk", code: "IVA" },
    { value: "ternopil", label: "Ternopil", code: "TER" },
    { value: "lutsk", label: "Lutsk", code: "LUT" },
  ],
  "united-kingdom": [
    { value: "london", label: "London", code: "LON" },
    { value: "manchester", label: "Manchester", code: "MAN" },
    { value: "birmingham", label: "Birmingham", code: "BIR" },
    { value: "leeds", label: "Leeds", code: "LEE" },
    { value: "glasgow", label: "Glasgow", code: "GLA" },
    { value: "liverpool", label: "Liverpool", code: "LIV" },
    { value: "bristol", label: "Bristol", code: "BRI" },
    { value: "sheffield", label: "Sheffield", code: "SHE" },
    { value: "edinburgh", label: "Edinburgh", code: "EDI" },
    { value: "leicester", label: "Leicester", code: "LEI" },
    { value: "coventry", label: "Coventry", code: "COV" },
    { value: "bradford", label: "Bradford", code: "BRA" },
    { value: "cardiff", label: "Cardiff", code: "CAR" },
    { value: "belfast", label: "Belfast", code: "BEL" },
    { value: "nottingham", label: "Nottingham", code: "NOT" },
    { value: "newcastle", label: "Newcastle", code: "NEW" },
    { value: "southampton", label: "Southampton", code: "SOU" },
    { value: "brighton", label: "Brighton", code: "BRI" },
    { value: "reading", label: "Reading", code: "REA" },
    { value: "oxford", label: "Oxford", code: "OXF" },
  ],
  "united-states": [
    { value: "new-york", label: "New York", code: "NEW" },
    { value: "los-angeles", label: "Los Angeles", code: "LOS" },
    { value: "chicago", label: "Chicago", code: "CHI" },
    { value: "houston", label: "Houston", code: "HOU" },
    { value: "phoenix", label: "Phoenix", code: "PHO" },
    { value: "philadelphia", label: "Philadelphia", code: "PHI" },
    { value: "san-antonio", label: "San Antonio", code: "SAN" },
    { value: "san-diego", label: "San Diego", code: "SAN" },
    { value: "dallas", label: "Dallas", code: "DAL" },
    { value: "san-jose", label: "San Jose", code: "SAN" },
    { value: "austin", label: "Austin", code: "AUS" },
    { value: "jacksonville", label: "Jacksonville", code: "JAC" },
    { value: "fort-worth", label: "Fort Worth", code: "FOR" },
    { value: "columbus", label: "Columbus", code: "COL" },
    { value: "charlotte", label: "Charlotte", code: "CHA" },
    { value: "san-francisco", label: "San Francisco", code: "SAN" },
    { value: "indianapolis", label: "Indianapolis", code: "IND" },
    { value: "seattle", label: "Seattle", code: "SEA" },
    { value: "denver", label: "Denver", code: "DEN" },
    { value: "boston", label: "Boston", code: "BOS" },
    { value: "washington", label: "Washington", code: "WAS" },
    { value: "nashville", label: "Nashville", code: "NAS" },
    { value: "detroit", label: "Detroit", code: "DET" },
    { value: "portland", label: "Portland", code: "POR" },
  ],
  "vietnam": [
    { value: "ho-chi-minh-city", label: "Ho Chi Minh City", code: "HOC" },
    { value: "hanoi", label: "Hanoi", code: "HAN" },
    { value: "da-nang", label: "Da Nang", code: "DAN" },
    { value: "hai-phong", label: "Hai Phong", code: "HAI" },
    { value: "can-tho", label: "Can Tho", code: "CAN" },
    { value: "bien-hoa", label: "Bien Hoa", code: "BIE" },
    { value: "hue", label: "Hue", code: "HUE" },
    { value: "nha-trang", label: "Nha Trang", code: "NHA" },
    { value: "buon-ma-thuot", label: "Buon Ma Thuot", code: "BUO" },
    { value: "vung-tau", label: "Vung Tau", code: "VUN" },
    { value: "quy-nhon", label: "Quy Nhon", code: "QUY" },
    { value: "thu-dau-mot", label: "Thu Dau Mot", code: "THU" },
    { value: "long-xuyen", label: "Long Xuyen", code: "LON" },
    { value: "thai-nguyen", label: "Thai Nguyen", code: "THA" },
    { value: "nam-dinh", label: "Nam Dinh", code: "NAM" },
    { value: "vinh", label: "Vinh", code: "VIN" },
    { value: "rach-gia", label: "Rach Gia", code: "RAC" },
    { value: "ha-long", label: "Ha Long", code: "HAL" },
    { value: "pleiku", label: "Pleiku", code: "PLE" },
    { value: "da-lat", label: "Da Lat", code: "DAL" },
  ],
};

const GENDER_OPTIONS: FilterOption[] = [
  ALL_OPTION,
  { value: "men", label: "Men", code: "M" },
  { value: "women", label: "Women", code: "W" },
];

const AGE_OPTIONS: FilterOption[] = [
  ALL_OPTION,
  { value: "18-24", label: "18–24", code: "18-24" },
  { value: "25-34", label: "25–34", code: "25-34" },
  { value: "35-44", label: "35–44", code: "35-44" },
];

function sortAlpha(options: FilterOption[]): FilterOption[] {
  return [...options].sort((a, b) => a.label.localeCompare(b.label));
}

function sortAllFirst(options: FilterOption[]): FilterOption[] {
  const all = options.filter((o) => o.value === "all");
  const rest = options
    .filter((o) => o.value !== "all")
    .sort((a, b) => a.label.localeCompare(b.label));
  return [...all, ...rest];
}

/** City wheel options for active country */
export function getCityOptions(country: string): FilterOption[] {
  if (country === "all") {
    const seen = new Map<string, FilterOption>();
    for (const cities of Object.values(CITIES_BY_COUNTRY)) {
      for (const city of cities) {
        if (!seen.has(city.value)) seen.set(city.value, city);
      }
    }
    return [ALL_OPTION, ...sortAlpha([...seen.values()])];
  }
  const cities = CITIES_BY_COUNTRY[country] ?? [];
  return [ALL_OPTION, ...sortAlpha(cities)];
}

const ALL_CITIES: FilterOption[] = (() => {
  const seen = new Map<string, FilterOption>();
  for (const cities of Object.values(CITIES_BY_COUNTRY)) {
    for (const city of cities) {
      if (!seen.has(city.value)) seen.set(city.value, city);
    }
  }
  return sortAlpha([...seen.values()]);
})();

export const FILTER_OPTIONS: Record<FilterKey, FilterOption[]> = {
  city: [ALL_OPTION, ...ALL_CITIES],
  country: sortAllFirst([ALL_OPTION, ...COUNTRY_OPTIONS]),
  gender: GENDER_OPTIONS,
  age: AGE_OPTIONS,
};

export const DEFAULT_FILTERS: DiscoveryFilters = {
  city: "all",
  country: "all",
  gender: "all",
  age: "all",
};

export const FILTER_KEYS: FilterKey[] = ["country", "city", "gender", "age"];

export function getFilterOption(
  key: FilterKey,
  value: string,
): FilterOption | undefined {
  if (key === "city") {
    if (value === "all") return ALL_OPTION;
    return ALL_CITIES.find((o) => o.value === value);
  }
  return FILTER_OPTIONS[key].find((o) => o.value === value);
}

export function getFilterCode(key: FilterKey, value: string): string {
  return getFilterOption(key, value)?.code ?? value;
}

export function getFilterLabel(key: FilterKey, value: string): string {
  return getFilterOption(key, value)?.label ?? value;
}

/** Apply filter change; reset city→all when country cascade invalidates it */
export function applyFilterChange(
  filters: DiscoveryFilters,
  key: FilterKey,
  value: string,
): DiscoveryFilters {
  const next: DiscoveryFilters = { ...filters, [key]: value };
  if (key === "country") {
    const cityOk = getCityOptions(value).some((o) => o.value === next.city);
    if (!cityOk) next.city = "all";
  }
  return next;
}

/** Meta location: city label, else country, else All */
export function getFilterMetaLabel(filters: DiscoveryFilters): string {
  if (filters.city !== "all") return getFilterLabel("city", filters.city);
  if (filters.country !== "all")
    return getFilterLabel("country", filters.country);
  return "All";
}
